---
- name: add IP instances to hosts file
  hosts: localhost
  gather_facts: False
  become: yes
  become_user: root
  remote_user: ubuntu

  roles:
    - add_host

- name: Build application
  hosts: build_istance
  become: yes
  become_user: root
  remote_user: ubuntu

  roles:
    - build_app
  
- name: Run application
  hosts: run_istance
  become: yes
  become_user: root
  remote_user: ubuntu


  vars:
    image_name:  boxfuse_app
    image_fname: rickyticky2/boxfuse_app:v1

  tasks:
    - name: install docker.io
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Run docker image
      docker_container:
        name: "{{ image_name }}"
        image: "{{ image_fname }}"
        ports:
          - 8080:8080
        state: started
