---
- name: Create instances
  hosts: localhost
  gather_facts: False
  become: yes
  become_user: root
  remote_user: ubuntu

  roles:
    - addhosts


#  - name: Ensure Docker is started
 #   service:
 #     name: docker
 #     state: started

- name: Build application
  hosts: build_istance
  become: yes
  become_user: root
  remote_user: ubuntu

  roles:
    - build_app
  

- name: Run application
  hosts: run_istance
  become: yes
  become_user: root
  remote_user: ubuntu

  tasks:
    - name: Run docker image
      docker_container:
        name: boxfuse_app
        image: rickyticky2/boxfuse_app:v1
        ports:
          - 8080:8080
        state: started
